/**
 * antidetect-preload.js
 *
 * THIS FILE IS GENERATED AT RUNTIME by main.js (app.whenReady).
 * The actual content is written to the temp dir and registered via
 * session.registerPreloadScript() so it runs in every page frame
 * BEFORE any inline page script — including Google's bot-detection code.
 *
 * Do not edit this file; your changes will be overwritten on the next launch.
 */
'use strict';
// placeholder — overwritten at startup

